version: '3'

services:

  stocks:
    image: stocks
    restart: always
    build:
      context: ./Stocks
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    networks:
      - backend
    container_name: stocks
    volumes:
      - $PWD/Stocks:/usr/local/stocks
      - ignore-stocks:/usr/local/stocks/node_modules

  gateway:
    image: gateway
    restart: always
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - backend
    depends_on:
      - stocks
    container_name: gateway
    volumes:
      - $PWD/Gateway:/usr/local/gateway
      - ignore-gateway:/usr/local/gateway/node_modules

networks:
  backend:
    driver: bridge

volumes:
  ignore-stocks:
  ignore-gateway: